
#Do not remove this file - needed by the installer!
#Fri Nov 01 03:40:58 PDT 2024
#Printing configs
acm.db.hostname=localhost
acm.db.name=standaloneDB
acm.db.password=
acm.db.permissionstablename=ACM_USERGROUPRESOURCE
acm.db.port=9003
acm.db.schema=PUBLIC
acm.db.username=SA
acm.group.name=Administrators
acm.schema=Pinpoint
acm.url=http://localhost:8086/acmserver
app.db.permissionsviewname=VIEW_USERGROUPRESOURCE
app.db.schema=PUBLIC
app-running-model=standalone
audit.enabled=false
auto.release.publication.type=CRDM,CMM
client.content.header.logo.path.mobile=client-logo/logo_mobile.svg
client.logo.path.mobile=client-logo/logo.svg
client.logo.path=client-logo/logo.svg
default.organization.ncage=SYS
download.destination=${cor.workdir}/data/pp
eula.content.path=eula-content/eula.html
extract.destination=${cor.workdir}/data/pp
import.publication.thread.count=1
imports.scheduled.time= */2 * * * * ?
hibernate.dialect=com.flatirons.commons.hibernate.dialect.HsqldbDialect
hibernate.format_sql=true
# Prevent Hibernate from trying to create or validate the database
hibernate.hbm2ddl.auto=none
hibernate.hbm2ddlauto=none
# Prevent Liquibase from trying to upgrade the database
dbupgrade.auto=false
acm.username=Guest
acm.password=RSA(E8+QRQOpP2JfbPYtT7/c4dmBzvPVybG8zBhnZCNQRk57qhXYOJx0c+xpdjiYeYXFbB97Zx2bFz6nib7ZqFpQhStaVlNDZua0LDCVGRDh7sIFPIP4Tw9XywMazENQgBMSFBpX7+Tt5qDUbyIbH8J9W6oKr71WXcLOwn6n3qyZjAo=)
hibernate.show_sql=false
hsqldb.path=${cor.workdir}/data/hsqldb/standaloneDB
import.neutral.package.location=${cor.workdir}/pinpoint-autoimport
includeAnchorsInTOC=false
insight.feedback.enable=false
jdbc.connectionTimeout=30000
jdbc.driverClassName=org.hsqldb.jdbcDriver
jdbc.idleTimeout=600000
jdbc.maxLifetime=1800000
jdbc.maxPoolSize=50
jdbc.minIdle=20
jdbc.password=
jdbc.url=jdbc\:hsqldb\:hsql\://localhost\:9003/standaloneDB
jdbc.username=SA
management.health.mail.enabled=false
management.health.rabbit.enabled=false
mobile.package.destination=${cor.workdir}/data/pp/mobile
mobile.publication.type=
ondemand.publications.download.limit=2
organization.space.destination=${cor.workdir}/data/pp/orgspace
pdf.output.destination=${cor.workdir}/data/pp_pdf
pinpoint.sync.authoring.time=0 0/5 * * * ?
pinpoint.sync.org.config.time=10 * * * * ?
pinpoint.sync.supplement.time=0 0/5 * * * ?
pp.user.eula.enabled=true
encrypt.pinpoint_package.enabled=true
printing.company.title=Rolls-Royce
printing.footer.content=revisionnumber,releasedate,printed
printing.footer.font-size=12
printing.footer.releaseDateFormat=MMM-dd-yyyy
printing.header.font-size=12
printing.landscape.html.table.attributes=8|10
printing.landscape.orientation.page.size=Tabloid
printing.landscape.orientation.publication.name=WDM,SSM,WM,ASM,AWM
printing.margin.bottom=18mm
printing.margin.left=2mm
printing.margin.right=2mm
printing.margin.top=18mm
printing.pdf.show.footerwarningcontent=true
printing.pdf.show.revisiondetails=true
printing.plugin.path=bin/wkhtmltopdf/wkhtmltopdf.exe
printing.portrait.orientation.page.size=Letter
printing.revBar.class.add=oembar.png
printing.revBar.class.changeMark_fontColor_OEM=oembar.png
printing.revBar.class.coc_changeMark=cocbar.gif
printing.revBar.class.modify=oembar.png
printing.zoom.value=1.2
publications.lock.offline.duration=-1
show.revision.number=custom
show.warning.message.offline=false
solr.server.url=http://localhost:8085/solr
spring.application.admin.enabled=false
spring.application.admin.jmx-name=org.springframework.boot\:type\=Admin,name\=pp
spring.application.name=pp
spring.jmx.default-domain=pp
spring.jmx.enabled=false
