# Predictive search
pinpoint.predictive.search.cross.check=true
pinpoint.predictive.search.first.part.suggestions=true
pinpoint.predictive.search.default.misspelling.limit=10
pinpoint.predictive.search.languages=${cor.configdir}/predictivesearch/language.json
pinpoint.predictive.search.solr.server=http://localhost:8085/solr
pinpoint.predictive.search.history=${cor.workdir}/data/pp/predictivesearch/history.json
pinpoint.predictive.search.max.response.timeout=15000
pinpoint.predictive.search.pinpoint.solr.server=http://localhost:8085/solr
pinpoint.predictive.search.enable.cache=true
pinpoint.predictive.search.single.first.part.timeout=7000000
pinpoint.predictive.search.core.timeout=100000000
pinpoint.predictive.search.solr.cores.path=${cor.workdir}/solr_home
pinpoint.predictive.search.default.misspelling.first.part.limit=10

# application.properties
#indexing solr
pinpoint.solr.core.indexed=pinpoint_server
#second solr
solr.core.misspellings=misspellings_core
solr.core.synonyms=synonyms_core
solr.core.abbreviations=abbreviations_core
solr.core.acronyms=acronyms_core
#jsondoc(playground + info)
jsondoc.version=1.0
jsondoc.basePath=http://localhost:8085/predictivesearch
jsondoc.packages[0]=com.flatirons.pinpoint.predictive.search
#logging
logging.level.org.springframework=ERROR
logging.level.com.flatirons.pinpoint.predictive.search=INFO
logging.file.name=${cor.logdir}/suggestions.log
logging.pattern.file=%d %p %c{1.} [%t] %m%n
#actuator
management.server.servlet.context-path=/actuator
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true
management.health.defaults.enabled=false
management.health.consul.enabled=false
management.endpoint.health.show-details=always
debug=false
