#Updated by Pinpoint Standalone startup process
#Fri Jul 25 11:48:01 CEST 2025
pinpoint.port.ssl=9193
stop.on.error=true
pp.main.path=/pinpoint
update.configuration=true
ldap.port=10489
number.of.threads=1
acm.port.ssl=9191
hsqldb.port=9003
http.protocol=http
pinpoint.port=8085
autodetect.free.ports=true
parallel.startup=true
location.data=data
acm.port=8086
acm.main.path=/acmclient
host.name=localhost
location.bin=bin
config.variant=RR
location.log=logs
connector.compression=on
