# Pinpoint runtime config
--add-modules java.se
-Dtomcat.util.scan.StandardJarScanFilter.jarsToSkip=*.jar
-Xms256m
-Xmx1024m
"-Dcor.configdir=%EXEDIR%\conf"
"-Dcor.workdir=%EXEDIR%"
"-Dcor.logdir=%EXEDIR%\logs"
"-Dcor.statusdir=%EXEDIR%\logs"
"-Dsolr.log.dir=%EXEDIR%\logs"
"-Dredirect.stdout=true"
-Dfile.encoding=UTF8 -Duser.country=us -Duser.language=en
-Djava.util.logging.config.file=conf\logging.properties
-Dcor.use.tray=true
-classpath bin\tomcat\*;bin\pinpoint-standalone.jar 
com.flatirons.pinpoint.ietpconsole.IetpConsole
