# Generated by Django 5.0.7 on 2025-06-22 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normieapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('chemscan_specialist', 'ChemScan Specialist'), ('environmental_reviewer', 'Environmental Reviewer'), ('manufacturing_reviewer', 'Manufacturing Reviewer'), ('standards_officer', 'Standards Officer'), ('read_only', 'Read Only'), ('applicant', 'Applicant')], default='applicant', max_length=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_create_requests', models.BooleanField(default=True)),
                ('can_edit_requests', models.BooleanField(default=True)),
                ('can_delete_requests', models.BooleanField(default=False)),
                ('can_approve_requests', models.BooleanField(default=False)),
                ('can_perform_chemscan', models.BooleanField(default=False)),
                ('can_environmental_review', models.BooleanField(default=False)),
                ('can_manufacturing_review', models.BooleanField(default=False)),
                ('can_standards_review', models.BooleanField(default=False)),
                ('can_view_all_requests', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_view_audit_logs', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
