# Generated by Django 5.1.7 on 2025-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normieapp', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Mark as important/flagged'),
        ),
    ]
