"""

Workflow automation incoming CMSR (Consumable Material Supply Request)

1. Incoming CMSR includes:

- Email (.msg) with attachments:
    - Application form pdf (has a known structure), needs to be newest version
    - MSDS and TDS/PDS (by parsing the text)
    - MSDS needs to be in german, needs to be not less than 2 years old (parse for text and dates)
    - other documents, like certification documents/extrations (COC)

CMSR\
    Application form\
        - Antragsnummer
        - TKZ
        - Benennung
        - Produktzulassung nach Spezifikation
        - Antragserstellungsdatum
        - Antragsteller Abteilung
        - Einsatzort / Standort
        - Antragsteller Name
        - ...
    MSDS\
        - MSDS text
        - MSDS date
        - MSDS language
        - MSDS version
        - MSDS source
        - MSDS format
        - MSDS size
        - ...
    TDS\
    COC\
    ETC\


Update the excel file with new data


 update vs new (is the data new or is it an update)
 decide whether to add a new row or to update an existing row
 If Neubedarf, create a new row
 "5": {
         "name": "Kennzeichnung des Bedarfs",
         "type": "btn",
         "values": {
             "Neubedarf": "/0",
             "Bedarfsänderung": "/1"
         },
     },

Mappings (Data from pdf to merge to excel):

_column_mappings_verzeichnis:Verzeichnis-Sheet
"column to write to" : "data from pdf" (what to write to the column)

        "A": <Antragsnummer autogenerated>
        "B": <TKZ from TKZ-Sheet>
        "C": "TBD"
        "D": "13 - Erzeugnisrelevanz", (Ja/Nein)
        "E": -
        "F": "3 - Benennung", (text)
        "G": "18e - Produktzulassung nach Spezifikation", (text)
        "H": "2b - Antragserstellungsdatum", (text)
        "I": -
        "J": "2c - Antragsteller Abteilung", (text)
        "K": "12a - Einsatzort / Standort", (text)
        "L": "2a - Antragsteller Name", (text)
        "M": Hyperlink to PDF
        "N": "18b - Technisches Datenblatt", (if yes: hyperlink to file, else: nothing)
        "O": Hyperlink to COC
        "P": "18a - EU-Sicherheitsdatenblatt", (if yes: hyperlink to file, else: nothing)
        "Q": "18c - Gefährdungsbeurteilung", (if yes: hyperlink to file, else: nothing)
        "X": "15b - Bestellung über SAP?", (Nein: "Keine SAP Anlage", else: nothing)



TKZ generation:

_column_mappings_tkz:
        "A": <TKZ autogenerated>
        "B": "N/A"
        "C": - 
        "D": "3 - Benennung",
        "E": "18e - Produktzulassung nach Spezifikation",
        "F": "Antragsteller Name",
        "G": "Abteilung",
        "H": "Antragserstellungsdatum"


Workflow:

1. Parse PDF
- Extract data from PDF
- Map data to _column_mappings_verzeichnis
- Check if Neubedarf
- If Neubedarf, generate Antragsnummer & TKZ
- If Bedarfsänderung, update existing row (not yet planned)

2. Popuate Verzeichnis & TKZ
- Fetch last Antragsnummer and TKZ, reserve new number for both
- Populate Verzeicnis & TKZ with appropriate data













"""



