"""
Excel Writer Module for CMSR Automation

Writes extracted PDF data to TKZ and Verzeichnis Excel sheets
using the column mappings defined in the JSON files.
"""

import json
from pathlib import Path
from datetime import datetime
import win32com.client

def load_column_mappings():
    """
    Load column mappings for both TKZ and Verzeichnis sheets.
    """
    mappings_path = Path(__file__).parent / "mappings"
    
    # Load TKZ column mapping
    with open(mappings_path / "tkz.json", 'r', encoding='utf-8') as f:
        tkz_content = f.read().strip()
        # Handle the JSON format (it's missing the outer braces)
        if not tkz_content.startswith('{'):
            tkz_content = '{' + tkz_content + '}'
        tkz_mapping = json.loads(tkz_content)
    
    # Load Verzeichnis column mapping  
    with open(mappings_path / "verzeichnis.json", 'r', encoding='utf-8') as f:
        verzeichnis_content = f.read().strip()
        if not verzeichnis_content.startswith('{'):
            verzeichnis_content = '{' + verzeichnis_content + '}'
        verzeichnis_mapping = json.loads(verzeichnis_content)
    
    # Load PDF field mappings for column references
    with open(mappings_path / "pdf_fields.json", 'r', encoding='utf-8') as f:
        pdf_fields = json.load(f)
    
    return tkz_mapping, verzeichnis_mapping, pdf_fields

def create_tkz_row(pdf_data, new_tkz, pdf_fields):
    """
    Create a new row for the TKZ sheet based on PDF data.
    
    TKZ Column Mapping:
    A: Teilenummer (new TKZ)
    B: TO-Nummer (N/A)
    C: Benennung / Kategorie 
    D: Normkurzbezeichnung / Titel (field "3 - Benennung")
    E: Projekt (always "Allgemein")
    F: Name (Antragsteller Name)
    G: Abteilung
    H: Datum (Antragserstellungsdatum)
    I: Bemerkungen
    """
    
    tkz_row = {
        'A': new_tkz,  # Teilenummer
        'B': 'N/A',    # TO-Nummer
        'C': '',       # Benennung / Kategorie - empty for now
        'D': pdf_data.get('3', ''),      # "3 - Benennung"
        'E': 'Allgemein',                # Always "Allgemein"
        'F': pdf_data.get('2a', ''),     # "2a - Antragsteller Name"
        'G': pdf_data.get('2c', ''),     # "2c - Antragsteller Abteilung"
        'H': pdf_data.get('2b', ''),     # "2b - Antragserstellungsdatum"
        'I': ''        # Bemerkungen - empty for now
    }
    
    return tkz_row

def detect_location_from_pdf(pdf_data):
    """
    Detect location (OU or DW) from PDF text fields.
    Searches for "OU" (Oberursel) or "DW" (Dahlewitz) in relevant fields.
    """
    # Fields to search for location indicators
    location_fields = ['12a', '12b', '10', '2c']  # Einsatzort, Bereich, Verwendungszweck, Abteilung
    
    # Combine all relevant text
    search_text = ""
    for field in location_fields:
        if field in pdf_data and pdf_data[field]:
            search_text += f" {pdf_data[field]}"
    
    search_text = search_text.upper()
    
    # Check for location indicators
    if "OU" in search_text or "OBERURSEL" in search_text:
        return "OU"
    elif "DW" in search_text or "DAHLEWITZ" in search_text:
        return "DW"
    else:
        # Default fallback - check field 12a directly for any location info
        einsatzort = pdf_data.get('12a', '').strip()
        return einsatzort if einsatzort else ""

def create_verzeichnis_row(pdf_data, new_tkz, new_antragsnummer, pdf_fields):
    """
    Create a new row for the Verzeichnis sheet based on PDF data.
    
    Maps PDF fields to Verzeichnis columns according to the specification in excelwriter.py
    """
    
    # Detect location (OU or DW) from PDF text
    location = detect_location_from_pdf(pdf_data)
    
    # Create base row with all columns
    verzeichnis_row = {}
    
    # Column mappings from excelwriter.py comments:
    verzeichnis_row['A'] = new_antragsnummer  # Antragsnummer (autogenerated)
    verzeichnis_row['B'] = new_tkz           # TKZ from TKZ-Sheet
    verzeichnis_row['C'] = 'TBD'             # Freigabe status
    verzeichnis_row['D'] = pdf_data.get('13', '')  # "13 - Erzeugnisrelevanz" (Ja/Nein)
    verzeichnis_row['E'] = ''                # Empty column
    verzeichnis_row['F'] = pdf_data.get('3', '')   # "3 - Benennung"
    verzeichnis_row['G'] = pdf_data.get('18e', '') # "18e - Produktzulassung nach Spezifikation"
    verzeichnis_row['H'] = pdf_data.get('2b', '')  # "2b - Antragserstellungsdatum"
    verzeichnis_row['I'] = ''                # Abschluss - empty for now
    verzeichnis_row['J'] = pdf_data.get('2c', '')  # "2c - Antragsteller Abteilung"
    verzeichnis_row['K'] = location          # Detected location (OU or DW)
    verzeichnis_row['L'] = pdf_data.get('2a', '')  # "2a - Antragsteller Name"
    
    # Remove hyperlinks - leave empty for now
    verzeichnis_row['M'] = ''  # Antrag (was hyperlink to PDF)
    verzeichnis_row['N'] = ''  # Datenblatt (was hyperlink to TDS)
    verzeichnis_row['O'] = ''  # Produkt-zulassung (was hyperlink to COC)
    verzeichnis_row['P'] = ''  # SDB MSDS (was hyperlink to MSDS)
    verzeichnis_row['Q'] = ''  # Gefährdungsbeurteilung (was hyperlink to hazard assessment)
    
    # Fill remaining columns with empty values for now
    for col in ['R', 'S', 'T', 'U', 'V', 'W']:
        verzeichnis_row[col] = ''
    
    # Special handling for column X
    verzeichnis_row['X'] = 'Keine SAP Anlage' if pdf_data.get('15b') == 'Nein' else ''  # "15b - Bestellung über SAP?"
    
    return verzeichnis_row

def append_to_excel_file(file_path, new_row_data, sheet_name=None):
    """
    Append a new row to an Excel file using COM (Component Object Model) directly.
    Works natively with .xls, .xlsb, .xlsx files without any conversion.
    """
    print(f"Appending row to: {file_path}")
    
    try:
        # Create Excel COM object
        excel_app = win32com.client.Dispatch("Excel.Application")
        excel_app.Visible = False  # Run in background
        excel_app.DisplayAlerts = False  # Suppress alerts
        
        # Open workbook
        workbook = excel_app.Workbooks.Open(str(file_path.absolute()))
        
        # Select worksheet
        if sheet_name:
            worksheet = workbook.Worksheets(sheet_name)
        else:
            worksheet = workbook.Worksheets(1)  # First sheet
        
        # Find the next empty row
        last_row = worksheet.Cells(worksheet.Rows.Count, 1).End(-4162).Row  # xlUp = -4162
        next_row = last_row + 1
        
        print(f"Writing to row {next_row}")
        
        # Write data to the row
        for col_letter, value in new_row_data.items():
            if col_letter.isalpha() and len(col_letter) == 1:  # Single letter columns A-Z
                col_num = ord(col_letter.upper()) - ord('A') + 1
                cell = worksheet.Cells(next_row, col_num)
                cell.Value = value
                print(f"  {col_letter}{next_row} = {value}")
        
        # Save and close
        workbook.Save()
        workbook.Close()
        excel_app.Quit()
        
        print(f"✓ Successfully added row to {file_path}")
        return True
        
    except Exception as e:
        print(f"✗ Error writing to {file_path}: {e}")
        # Clean up Excel process if it's still running
        try:
            if 'excel_app' in locals():
                excel_app.Quit()
        except:
            pass
        return False

def write_to_excel_sheets(pdf_data, new_tkz, new_antragsnummer, tkz_file_path, verzeichnis_file_path):
    """
    Write PDF data to both TKZ and Verzeichnis Excel sheets.
    Sequential processing: TKZ first, then Verzeichnis.
    """
    print("=== Writing to Excel Sheets ===")
    
    # Load mappings
    tkz_mapping, verzeichnis_mapping, pdf_fields = load_column_mappings()
    
    # Create row data
    tkz_row = create_tkz_row(pdf_data, new_tkz, pdf_fields)
    verzeichnis_row = create_verzeichnis_row(pdf_data, new_tkz, new_antragsnummer, pdf_fields)
    
    print("Created row data:")
    print(f"  TKZ row: {tkz_row}")
    print(f"  Verzeichnis row keys: {list(verzeichnis_row.keys())}")
    
    # Step 1: Write to TKZ sheet
    print("\nStep 1: Writing to TKZ sheet...")
    tkz_success = append_to_excel_file(Path(tkz_file_path), tkz_row)
    
    if not tkz_success:
        print("✗ Failed to write TKZ entry - aborting")
        return False
    
    # Step 2: Write to Verzeichnis sheet
    print("\nStep 2: Writing to Verzeichnis sheet...")
    verzeichnis_success = append_to_excel_file(Path(verzeichnis_file_path), verzeichnis_row)
    
    if not verzeichnis_success:
        print("✗ Failed to write Verzeichnis entry")
        print("⚠ Warning: TKZ entry was created but Verzeichnis entry failed")
        print("⚠ Manual cleanup may be required")
        return False
    
    print("✓ Successfully wrote to both Excel sheets")
    return True

# Test function
if __name__ == "__main__":
    # Test data
    test_pdf_data = {
        '1': 'TEST001',
        '2a': 'Test User',
        '2b': '2025-01-01',
        '2c': 'Test Department',
        '3': 'Test Product',
        '5': 'Neubedarf',
        '12a': 'Test Location',
        '13': 'Ja',
        '15b': 'Nein',
        '18a': 'Ja',
        '18b': 'Ja',
        '18c': 'Nein',
        '18e': 'Test Specification'
    }
    
    # Test file paths
    base_path = Path(__file__).parent
    tkz_path = base_path / "TKZ.xls"
    verzeichnis_path = base_path / "Verzeichnis.xlsb"
    
    if tkz_path.exists() and verzeichnis_path.exists():
        print("Testing Excel writing with sample data...")
        success = write_to_excel_sheets(
            test_pdf_data, 
            "01044398", 
            "159/2025",
            tkz_path,
            verzeichnis_path
        )
        print(f"Test result: {'SUCCESS' if success else 'FAILED'}")
    else:
        print("Excel files not found for testing")
