jdbc.url=jdbc\:hsqldb\:file\:./data/hsqldb/ppdb
jdbc.username=SA
jdbc.password=

hibernate.dialect=com.flatirons.commons.hibernate.dialect.HsqldbDialect
jdbc.driverClassName=org.hsqldb.jdbcDriver

server.port=9300

data_manager_resource_path_server=http://localhost:9200/api

acm.url=http://localhost:9100
acm.schema=Pinpoint
acm.username=acm-admin
acm.password=CorAdm123!

download.destination=data/download_data
extract.destination=data/extract_data
mobile.package.destination=data/mobile_download

audit.rabbitmq.fallback.username=rabbitmq-admin
audit.rabbitmq.fallback.password=admin123
