jdbc.driverClassName=org.postgresql.Driver
jdbc.maxPoolSize=50
jdbc.minIdle=20
jdbc.connectionTimeout=30000
jdbc.idleTimeout=600000
jdbc.maxLifetime=1800000

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=false
hibernate.format_sql=true

#enable automatic database schema upgrade not not
dbupgrade.auto=true

#Control if Pinpoint Server is running as a master instance. 
#Only it is running as a master instance and you have configured data manager server, it imports publications from Data Manager
master=true

#Publication package download, extract and archive destination
download.destination=/opt/apps/tomcat/DownloadData
extract.destination=/opt/apps/tomcat/DownloadData
archive.destination=/opt/apps/tomcat/DownloadData
mobile.package.destination=/opt/apps/tomcat/DownloadData
mobile.publication.type=AMM,TSM,CRDM,FRMFIM,AIRBOOK
filter.columns.name=
spring.main.allow-bean-definition-overriding=true
acm.schema=Pinpoint

#For standalone model must not execute delete publication and library action
#App type [server,standalone]
app-running-model=server

#set false to hide anchors in toc
includeAnchorsInTOC=true
# PDF Printing
#set pdf plugin path, if it is empty, application will get pdf plugin from classpath/wkhtmltopdf/os/XXX/wkhtmltopdf
#printing.plugin.path=
printing.header.font-size=12px
printing.footer.font-size=12px
printing.margin.top=18mm
printing.margin.bottom=10mm
printing.margin.left=2mm
printing.margin.right=2mm
#set pager size in mm:  A3 (297 x 420 mm), Tabloid (279.4 x 431.8 mm, 11 x 17 inches)
#For more paper size, please refer http://doc.qt.io/qt-4.8/qprinter.html#PaperSize-enum
printing.landscape.orientation.page.size=Tabloid
printing.portrait.orientation.page.size=A4
printing.landscape.orientation.publication.name=WDM,SSM,WM,ASM,AWM
# set html table attributes to print landscape pdf, format: html table width(inch)|html table columns
printing.landscape.html.table.attributes=8|10
#rev bars. format: pdf.revBar.class.className=img path
printing.revBar.class.modify=oembar.png
printing.revBar.class.add=oembar.png
printing.revBar.class.coc_changeMark=cocbar.gif
printing.company.title=Company Title
# set pdf font size. If value is 0.9, then font size is 9pt. If value is 1, then font size is 10pt. If value is 1.1, then font size is 11pt.
printing.zoom.value=1
printing.thread.count=3
# set printing javascript-delay to Wait some milliseconds for javascript finish.
printing.javascript.delay=500
printing.pdf.show.footerwarningcontent=false
printing.pdf.show.revisiondetails=true

# options to control access and default behavior for strikeout non-effective content feature (RRMROPP-1202)
printing.nonEffectiveContent.optionEnabled=true
printing.nonEffectiveContent.defaultValue=false

# A list of types of publications supports auto release feature
auto.release.publication.type=CRDM,CMM

# Predict how much disk space is needed to complete the publication import. 8 means it needs 8 times disk space of the publication zip package size 
disk.space.ratio=8

# Decides whether EULA feature is enabled or not (accepted values - true, false)
pp.user.eula.enabled=false

publication.ipd.type=IPD,AIPC,IPC,Panasonic_IPD,EIPC,EIPD

enable.printing.graphic.inline=false

#RabbitMQ properties for Audit Manager
audit.routingKey=PpRoutingKey
audit.sourceApplication=PP

#Events for Audit Manager
audit.event.document_viewed=GET||content/publication/<publication_id>/refkey/<refkey>/type/<type>
audit.event.document_acknowledged=POST||acknowledgement/readsign/sign
audit.event.document_to_be_acknowledged=POST||acknowledgement/admin/save

audit.enabled=false
management.health.rabbit.enabled=${audit.enabled}
management.security.enabled=false
management.context-path=/actuator
endpoints.enabled=false
endpoints.health.enabled=true
endpoints.info.enabled=true

#fetch Publication Scheduled time
fetch.pub.scheduled.time = 00 * * * * ?
download.scheduled.time= 15 * * * * ?
extract.scheduled.time= 30 * * * * ?
symlink.scheduled.time = 00 * * * * ?
imports.scheduled.time= 45 * * * * ?
archive.scheduled.time= 00 * * * * ?
release.scheduled.time= 00 * * * * ?

#Sync and update publication scheduled time
update.scheduled.time = 0 0 * ? * *

#expire monitor schedule
expire.monitor.scheduled.time= 0 0 1 * * ?

#recover schedule
recovery.scheduled.time= 0 0/10 * * * ?

#Pinpoint components (Annotations...) schedule
pinpoint.sync.scheduled.time = 00 * * * * ?

#Pinpoint components (Supplements...) schedule
pinpoint.sync.supplement.time = 0 0 0/1 * * ?

#Pinpoint components (Authoring...) schedule
pinpoint.sync.authoring.time = 0 0/1 * * * ?

#Pinpoint components (PreferredRevision...) schedule
pinpoint.sync.org.config.time = 10 * * * * ?

#schedule load pinpoint neutral package from local directory
pinpoint.neutral.package.load.scheduled.time = 30 * * * * ?

# Attachment Notification Scheduled time
notify.attachment.scheduled.time = 00 * * * * ?

# Spring mail settings - Has to be configured for pinpoint server startup
spring.mail.host=smtp.gmail.com
spring.mail.username=GoogleEmail@gmail.com
spring.mail.password=apppassword
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.debug=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.socketFactory.port=587
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
default.organization.ncage=INVALID_NCAGE_VALUE_PLEASE_CONFIGURE

spring.jmx.default-domain=pp

#Additional properties needed as part of PORTALMIG-441, minimum required to create a local view into ACM
app.db.schema=pinpoint
acm.db.schema=acm

#Additional properties needed as part of PORTALMIG-441, additional require if the ACM schema is not in the 
#DB instance, in which case a DBLINK must be created - requires external DB's username and password.
acm.db.hostname=localhost
acm.db.port=5432
acm.db.name=localdb
acm.db.username=postgres
acm.db.password=admin123

#standlone lock period
publications.lock.offline.duration=-1

#warning message turn on/off while accessing publications in Pinpoint stand alone.
show.warning.message.offline=false

# Filter assertion response when 'condition' criterion is missing in product.
filter.assert.missing.condition=true

#configurations to display configured thumbnails. Note, this configuration takes precedence and will display configured thumbnail, even if graphic has a thumbnail in the neutral package.
graphic.thumbnail.default.jpg =default_jpg.jpg
graphic.thumbnail.default.jpeg =default_jpg.jpg
graphic.thumbnail.default.gif =default_gif.jpg
graphic.thumbnail.default.svg =default_svg.jpg
graphic.thumbnail.default.x3d =default_x3d.jpg


# delete the pinpoint preview publication and library
pinpoint.delete.preview.enable = true
pinpoint.delete.preview.library = true

# no of threads for parallel document processing during Publication import
import.document.thread.count=1
# queue capacity for for parallel document processing, higher capacity will provide faster single-import throughput, lower capacity will provide faster switching between parallel-imports
import.document.queue.capacity=10

# no of parallel Publication imports allowed and priority publication types
import.publication.thread.count=1
import.publication.priority.types=CRDM

#includeGeneratedSheetPrefix
include.generatedFigure.prefix = true
include.generatedSheet.prefix = true
use.content.sheet.titles = false
fallback.figure.title = Expand For Sheets

#interval for scheduled archive job
archive.job.scheduled.time= 00 * * * * ?

pinpoint.retry.import.count=2

# disable showing the popup when the csnLink found the multiple targets
disableMultipleReferencePopup=false
# Prevent Hibernate from trying to create or validate the database
hibernate.hbm2ddl.auto=none
hibernate.hbm2ddlauto=none
# Prevent Liquibase from trying to upgrade the database
dbupgrade.auto=false
acm.username=Guest
acm.password=RSA(gS0xDn/xG4B4ke2+ALoG5EwFL2F45Fp7CMScH00htbMBVj9PBa0xpGNlTdNu5aDgcH7MR4g0BZhMl+iM1itVWN6BUDsNWttkEBkArxEudnLyzfgJ5yxv7JFHxpZiaMrvZlHtuhjaV60ciOXl4sAHhno4NbyWIdE8fsHMdGL5IKY=)
