jdbc.url=jdbc\:hsqldb\:file\:./data/hsqldb/acmdb
jdbc.username=SA
jdbc.password=

hibernate.dialect=org.hibernate.dialect.HSQLDialect
jdbc.driverClassName=org.hsqldb.jdbcDriver
server.port=9100

audit.rabbitmq.fallback.username=rabbitmq-admin
audit.rabbitmq.fallback.password=admin123

acm.username=acm-admin
acm.password=CorAdm123!
acm.server.url=http://localhost:9100