# Configuration file for Access Control Module
authenticationprovider=LDAP
# Database
jdbc.driverClassName=org.postgresql.Driver

jdbc.maxPoolSize=30
jdbc.minIdle=10
jdbc.connectionTimeout=30000
jdbc.idleTimeout=600000
jdbc.maxLifetime=1800000

# Hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Audit Manager
audit.routingKey=AcmRoutingKey
audit.sourceApplication=ACM

#Events for Audit Manager
audit.event.resource_uri_details=POST||resources
audit.event.user_resource_privilege_1=POST||usergroups/<usergroupid>/privileges
audit.event.user_resource_privilege_2=POST||usergroups/privileges
audit.event.user_resource_privilege_delete=DELETE||usergroups/<usergroupid>/privileges

logging.level.org.hibernate=warn
logging.level.org.hibernate.sql=warn

audit.enabled=false
management.health.rabbit.enabled=${audit.enabled}
management.context-path=/actuator
management.security.enabled=false
endpoints.enabled=false
endpoints.health.enabled=true
endpoints.info.enabled=true

user.claims.acm-admin={"groups"\:["ACM","DM","PP"]}

spring.jmx.default-domain=acm

#Guest Enabler properties
# Prevent Hibernate from trying to create or validate the database
hibernate.hbm2ddl.auto=none
hibernate.hbm2ddlauto=none
# Prevent Liquibase from trying to upgrade the database
dbupgrade.auto=false
acm.username=Guest
acm.password=RSA(a5wYL6K1kxyw4w6n9Z33Tw4YS+jjb3hbC6GmHO2dkPXdhGlYA8VnK1obzX9c1Wq9JsN4WisDq1XM6EOD8gghxs2pqKD6CIn5CMQUlLvspM1QeRp1F+nJxXkHXQI0Ut85/YJh8vLb+IpwZmGQvg28PD87hF8MSluACn0GRz1GPSQ=)
# Guest Access Properties
acm.guest.featureEnabled=true
acm.guest.switchAccountsEnabled=false
acm.guest.username=Guest
acm.guest.password=RSA(hPRZL53O4scXdTZtvs7G0ESmRDXPrKOkascOwBqo9IMgj89GKUtgBf/FQ05N/AYPi7sZWBfqJPt/wDpFAJMiivdCAtqhcwscg3cGl5basv1zfVtAXZ415FZiR/6aXzQHlRUhteTM7rsbqFF2C8XcYdD6T/yvJ2GYeH6vOtr+2dk=)

#Access key validity in days - default value is 30 days
acm.accesskey.validDays=30

#Access key clean time period - default time period is 10 minutes
acm.accesskey.cleanInterval=10

scheme.map.am=Audit Manager
scheme.map.pp=Pinpoint
scheme.map.dm=Data Manager
scheme.map.acm=Access Control

spring.main.allow-bean-definition-overriding=true

default.acm.groupname=Acmadministrators
default.acm.username=acm-admin
default.organization.ncage=INVALID_NCAGE_VALUE_PLEASE_CONFIGURE
